set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc rfile:../ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc id:1 order:EARLY scoped_inst:u_Clock_Gen/u_proc_sys_reset_16M384/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc rfile:../ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc id:2 order:EARLY scoped_inst:u_Clock_Gen/u_proc_sys_reset_1M024/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc rfile:../ip/Clock_Gen/proc_sys_reset_gen/proc_sys_reset_gen.xdc id:3 order:EARLY scoped_inst:u_Clock_Gen/u_proc_sys_reset_32M768/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/ip/Clock_Gen/clk_wiz_32M768/clk_wiz_32M768.xdc rfile:../ip/Clock_Gen/clk_wiz_32M768/clk_wiz_32M768.xdc id:4 order:EARLY scoped_inst:u_Clock_Gen/u_clk_wiz_32M768/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/ip/Clock_Gen/clk_wiz_128M/clk_wiz_128M.xdc rfile:../ip/Clock_Gen/clk_wiz_128M/clk_wiz_128M.xdc id:5 order:EARLY scoped_inst:u_Clock_Gen/u_clk_wiz_128M/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/constraints/lt_zynq_V200.xdc rfile:../constraints/lt_zynq_V200.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:12 order:LATE scoped_inst:u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:13 order:LATE scoped_inst:u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:14 order:LATE scoped_inst:u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
current_instance u_Clock_Gen/u_proc_sys_reset_16M384/U0
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance u_Clock_Gen/u_proc_sys_reset_1M024/U0
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance u_Clock_Gen/u_proc_sys_reset_32M768/U0
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance u_Clock_Gen/u_clk_wiz_32M768/inst
set_property src_info {type:SCOPED_XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.078
current_instance
current_instance u_Clock_Gen/u_clk_wiz_128M/inst
set_property src_info {type:SCOPED_XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
set_property src_info {type:XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports clk_prog_clk0]
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports clk_prog_clk1]
set_property src_info {type:XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports clk_prog_clk2]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk0]
set_property src_info {type:XDC file:6 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk1]
set_property src_info {type:XDC file:6 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk_prog_clk2]
set_property src_info {type:XDC file:6 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports SFP_TX_Fault]
set_property src_info {type:XDC file:6 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports SFP_TX_DIS]
set_property src_info {type:XDC file:6 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports SFP_SDA]
set_property src_info {type:XDC file:6 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports SFP_SCL]
set_property src_info {type:XDC file:6 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports SFP_PRESENT]
set_property src_info {type:XDC file:6 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports SFP_Rate_Select]
set_property src_info {type:XDC file:6 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports SFP_LOS]
set_property src_info {type:XDC file:6 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_TX_Fault]
set_property src_info {type:XDC file:6 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_TX_DIS]
set_property src_info {type:XDC file:6 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_SDA]
set_property src_info {type:XDC file:6 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_SCL]
set_property src_info {type:XDC file:6 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_PRESENT]
set_property src_info {type:XDC file:6 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_Rate_Select]
set_property src_info {type:XDC file:6 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SFP_LOS]
set_property src_info {type:XDC file:6 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports {LS_ADC2_DB[13]}]
set_property src_info {type:XDC file:6 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {LS_ADC2_DB[12]}]
set_property src_info {type:XDC file:6 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {LS_ADC2_DB[11]}]
set_property src_info {type:XDC file:6 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {LS_ADC2_DB[10]}]
set_property src_info {type:XDC file:6 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {LS_ADC2_DB[9]}]
set_property src_info {type:XDC file:6 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {LS_ADC2_DB[8]}]
set_property src_info {type:XDC file:6 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {LS_ADC2_DB[7]}]
set_property src_info {type:XDC file:6 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19 [get_ports {LS_ADC2_DB[6]}]
set_property src_info {type:XDC file:6 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P22 [get_ports {LS_ADC2_DB[5]}]
set_property src_info {type:XDC file:6 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {LS_ADC2_DB[4]}]
set_property src_info {type:XDC file:6 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21 [get_ports {LS_ADC2_DB[3]}]
set_property src_info {type:XDC file:6 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {LS_ADC2_DB[2]}]
set_property src_info {type:XDC file:6 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {LS_ADC2_DB[1]}]
set_property src_info {type:XDC file:6 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {LS_ADC2_DB[0]}]
set_property src_info {type:XDC file:6 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports LS_ADC2_CLK]
set_property src_info {type:XDC file:6 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22 [get_ports LS_ADC2_OTR]
set_property src_info {type:XDC file:6 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {LS_ADC1_DB[13]}]
set_property src_info {type:XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {LS_ADC1_DB[12]}]
set_property src_info {type:XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports {LS_ADC1_DB[11]}]
set_property src_info {type:XDC file:6 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports {LS_ADC1_DB[10]}]
set_property src_info {type:XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports {LS_ADC1_DB[9]}]
set_property src_info {type:XDC file:6 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {LS_ADC1_DB[8]}]
set_property src_info {type:XDC file:6 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {LS_ADC1_DB[7]}]
set_property src_info {type:XDC file:6 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {LS_ADC1_DB[6]}]
set_property src_info {type:XDC file:6 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {LS_ADC1_DB[5]}]
set_property src_info {type:XDC file:6 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W12 [get_ports {LS_ADC1_DB[4]}]
set_property src_info {type:XDC file:6 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports {LS_ADC1_DB[3]}]
set_property src_info {type:XDC file:6 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11 [get_ports {LS_ADC1_DB[2]}]
set_property src_info {type:XDC file:6 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA9 [get_ports {LS_ADC1_DB[1]}]
set_property src_info {type:XDC file:6 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {LS_ADC1_DB[0]}]
set_property src_info {type:XDC file:6 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports LS_ADC1_CLK]
set_property src_info {type:XDC file:6 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports LS_ADC1_OTR]
set_property src_info {type:XDC file:6 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[13]}]
set_property src_info {type:XDC file:6 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[12]}]
set_property src_info {type:XDC file:6 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[11]}]
set_property src_info {type:XDC file:6 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[10]}]
set_property src_info {type:XDC file:6 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[9]}]
set_property src_info {type:XDC file:6 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[8]}]
set_property src_info {type:XDC file:6 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[7]}]
set_property src_info {type:XDC file:6 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[6]}]
set_property src_info {type:XDC file:6 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[5]}]
set_property src_info {type:XDC file:6 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[4]}]
set_property src_info {type:XDC file:6 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[3]}]
set_property src_info {type:XDC file:6 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[2]}]
set_property src_info {type:XDC file:6 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[1]}]
set_property src_info {type:XDC file:6 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC2_DB[0]}]
set_property src_info {type:XDC file:6 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC2_CLK]
set_property src_info {type:XDC file:6 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC2_OTR]
set_property src_info {type:XDC file:6 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[13]}]
set_property src_info {type:XDC file:6 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[12]}]
set_property src_info {type:XDC file:6 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[11]}]
set_property src_info {type:XDC file:6 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[10]}]
set_property src_info {type:XDC file:6 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[9]}]
set_property src_info {type:XDC file:6 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[8]}]
set_property src_info {type:XDC file:6 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[7]}]
set_property src_info {type:XDC file:6 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[6]}]
set_property src_info {type:XDC file:6 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[5]}]
set_property src_info {type:XDC file:6 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[4]}]
set_property src_info {type:XDC file:6 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[3]}]
set_property src_info {type:XDC file:6 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[2]}]
set_property src_info {type:XDC file:6 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[1]}]
set_property src_info {type:XDC file:6 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_ADC1_DB[0]}]
set_property src_info {type:XDC file:6 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC1_CLK]
set_property src_info {type:XDC file:6 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_ADC1_OTR]
set_property src_info {type:XDC file:6 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports {LS_DAC2_DB[13]}]
set_property src_info {type:XDC file:6 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {LS_DAC2_DB[12]}]
set_property src_info {type:XDC file:6 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10 [get_ports {LS_DAC2_DB[11]}]
set_property src_info {type:XDC file:6 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {LS_DAC2_DB[10]}]
set_property src_info {type:XDC file:6 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {LS_DAC2_DB[9]}]
set_property src_info {type:XDC file:6 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports {LS_DAC2_DB[8]}]
set_property src_info {type:XDC file:6 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {LS_DAC2_DB[7]}]
set_property src_info {type:XDC file:6 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {LS_DAC2_DB[6]}]
set_property src_info {type:XDC file:6 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {LS_DAC2_DB[5]}]
set_property src_info {type:XDC file:6 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {LS_DAC2_DB[4]}]
set_property src_info {type:XDC file:6 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports {LS_DAC2_DB[3]}]
set_property src_info {type:XDC file:6 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y4 [get_ports {LS_DAC2_DB[2]}]
set_property src_info {type:XDC file:6 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {LS_DAC2_DB[1]}]
set_property src_info {type:XDC file:6 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {LS_DAC2_DB[0]}]
set_property src_info {type:XDC file:6 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports LS_DAC2_WRT]
set_property src_info {type:XDC file:6 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports LS_DAC2_CLK]
set_property src_info {type:XDC file:6 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports LS_DAC_MODE]
set_property src_info {type:XDC file:6 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {LS_DAC1_DB[13]}]
set_property src_info {type:XDC file:6 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {LS_DAC1_DB[12]}]
set_property src_info {type:XDC file:6 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {LS_DAC1_DB[11]}]
set_property src_info {type:XDC file:6 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports {LS_DAC1_DB[10]}]
set_property src_info {type:XDC file:6 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {LS_DAC1_DB[9]}]
set_property src_info {type:XDC file:6 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {LS_DAC1_DB[8]}]
set_property src_info {type:XDC file:6 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {LS_DAC1_DB[7]}]
set_property src_info {type:XDC file:6 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {LS_DAC1_DB[6]}]
set_property src_info {type:XDC file:6 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {LS_DAC1_DB[5]}]
set_property src_info {type:XDC file:6 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {LS_DAC1_DB[4]}]
set_property src_info {type:XDC file:6 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {LS_DAC1_DB[3]}]
set_property src_info {type:XDC file:6 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {LS_DAC1_DB[2]}]
set_property src_info {type:XDC file:6 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {LS_DAC1_DB[1]}]
set_property src_info {type:XDC file:6 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {LS_DAC1_DB[0]}]
set_property src_info {type:XDC file:6 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports LS_DAC1_WRT]
set_property src_info {type:XDC file:6 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports LS_DAC1_CLK]
set_property src_info {type:XDC file:6 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[13]}]
set_property src_info {type:XDC file:6 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[12]}]
set_property src_info {type:XDC file:6 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[11]}]
set_property src_info {type:XDC file:6 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[10]}]
set_property src_info {type:XDC file:6 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[9]}]
set_property src_info {type:XDC file:6 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[8]}]
set_property src_info {type:XDC file:6 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[7]}]
set_property src_info {type:XDC file:6 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[6]}]
set_property src_info {type:XDC file:6 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[5]}]
set_property src_info {type:XDC file:6 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[4]}]
set_property src_info {type:XDC file:6 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[3]}]
set_property src_info {type:XDC file:6 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[2]}]
set_property src_info {type:XDC file:6 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[1]}]
set_property src_info {type:XDC file:6 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC2_DB[0]}]
set_property src_info {type:XDC file:6 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC2_WRT]
set_property src_info {type:XDC file:6 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC2_CLK]
set_property src_info {type:XDC file:6 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[13]}]
set_property src_info {type:XDC file:6 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[12]}]
set_property src_info {type:XDC file:6 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[11]}]
set_property src_info {type:XDC file:6 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[10]}]
set_property src_info {type:XDC file:6 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[9]}]
set_property src_info {type:XDC file:6 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[8]}]
set_property src_info {type:XDC file:6 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[7]}]
set_property src_info {type:XDC file:6 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[6]}]
set_property src_info {type:XDC file:6 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[5]}]
set_property src_info {type:XDC file:6 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[4]}]
set_property src_info {type:XDC file:6 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[3]}]
set_property src_info {type:XDC file:6 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[2]}]
set_property src_info {type:XDC file:6 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[1]}]
set_property src_info {type:XDC file:6 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {LS_DAC1_DB[0]}]
set_property src_info {type:XDC file:6 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC1_WRT]
set_property src_info {type:XDC file:6 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC1_CLK]
set_property src_info {type:XDC file:6 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LS_DAC_MODE]
set_property src_info {type:XDC file:6 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports Audio_AD_SDOUT]
set_property src_info {type:XDC file:6 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports Audio_AD_SCLK]
set_property src_info {type:XDC file:6 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports Audio_AD_nRST]
set_property src_info {type:XDC file:6 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports Audio_AD_MCLK]
set_property src_info {type:XDC file:6 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4 [get_ports Audio_AD_M1]
set_property src_info {type:XDC file:6 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5 [get_ports Audio_AD_M0]
set_property src_info {type:XDC file:6 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1 [get_ports Audio_AD_LRCK]
set_property src_info {type:XDC file:6 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_SDOUT]
set_property src_info {type:XDC file:6 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_SCLK]
set_property src_info {type:XDC file:6 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_nRST]
set_property src_info {type:XDC file:6 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_MCLK]
set_property src_info {type:XDC file:6 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_M1]
set_property src_info {type:XDC file:6 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_M0]
set_property src_info {type:XDC file:6 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_AD_LRCK]
set_property src_info {type:XDC file:6 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports Audio_DA_SDIN]
set_property src_info {type:XDC file:6 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports Audio_DA_SCLK]
set_property src_info {type:XDC file:6 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports Audio_DA_LRCL]
set_property src_info {type:XDC file:6 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports Audio_DA_MCLK]
set_property src_info {type:XDC file:6 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_SDIN]
set_property src_info {type:XDC file:6 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_SCLK]
set_property src_info {type:XDC file:6 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_LRCL]
set_property src_info {type:XDC file:6 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Audio_DA_MCLK]
set_property src_info {type:XDC file:6 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {ETH_PL_RXD[3]}]
set_property src_info {type:XDC file:6 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {ETH_PL_RXD[2]}]
set_property src_info {type:XDC file:6 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {ETH_PL_RXD[1]}]
set_property src_info {type:XDC file:6 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {ETH_PL_RXD[0]}]
set_property src_info {type:XDC file:6 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports ETH_PL_RXCK]
set_property src_info {type:XDC file:6 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports ETH_PL_RXCTL]
set_property src_info {type:XDC file:6 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {ETH_PL_TXD[3]}]
set_property src_info {type:XDC file:6 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {ETH_PL_TXD[2]}]
set_property src_info {type:XDC file:6 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F21 [get_ports {ETH_PL_TXD[1]}]
set_property src_info {type:XDC file:6 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {ETH_PL_TXD[0]}]
set_property src_info {type:XDC file:6 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports ETH_PL_TXCK]
set_property src_info {type:XDC file:6 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports ETH_PL_TXCTL]
set_property src_info {type:XDC file:6 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports ETH_PL_MDIO]
set_property src_info {type:XDC file:6 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports ETH_PL_MDC]
set_property src_info {type:XDC file:6 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports ETH_PL_nRST]
set_property src_info {type:XDC file:6 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[3]}]
set_property src_info {type:XDC file:6 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[2]}]
set_property src_info {type:XDC file:6 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[1]}]
set_property src_info {type:XDC file:6 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_RXD[0]}]
set_property src_info {type:XDC file:6 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[3]}]
set_property src_info {type:XDC file:6 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[2]}]
set_property src_info {type:XDC file:6 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[1]}]
set_property src_info {type:XDC file:6 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_PL_TXD[0]}]
set_property src_info {type:XDC file:6 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_TXCTL]
set_property src_info {type:XDC file:6 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_TXCK]
set_property src_info {type:XDC file:6 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_RXCTL]
set_property src_info {type:XDC file:6 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_RXCK]
set_property src_info {type:XDC file:6 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_MDIO]
set_property src_info {type:XDC file:6 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_MDC]
set_property src_info {type:XDC file:6 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_PL_nRST]
set_property src_info {type:XDC file:6 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21  [get_ports GPIO_TH5]
set_property src_info {type:XDC file:6 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7   [get_ports GPIO_TH6]
set_property src_info {type:XDC file:6 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7   [get_ports GPIO_TH7]
set_property src_info {type:XDC file:6 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6   [get_ports GPIO_TH8]
set_property src_info {type:XDC file:6 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19  [get_ports GPIO_TH9]
set_property src_info {type:XDC file:6 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18  [get_ports GPIO_TH10]
set_property src_info {type:XDC file:6 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH5]
set_property src_info {type:XDC file:6 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH6]
set_property src_info {type:XDC file:6 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH7]
set_property src_info {type:XDC file:6 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH8]
set_property src_info {type:XDC file:6 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH9]
set_property src_info {type:XDC file:6 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_TH10]
set_property src_info {type:XDC file:6 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports McBSP0_CLKS0]
set_property src_info {type:XDC file:6 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports McBSP0_CLKX0]
set_property src_info {type:XDC file:6 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports McBSP0_FSX0]
set_property src_info {type:XDC file:6 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports McBSP0_DX0]
set_property src_info {type:XDC file:6 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports McBSP0_FSR0]
set_property src_info {type:XDC file:6 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports McBSP0_DR0]
set_property src_info {type:XDC file:6 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports McBSP1_DX1]
set_property src_info {type:XDC file:6 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_CLKS0]
set_property src_info {type:XDC file:6 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_CLKX0]
set_property src_info {type:XDC file:6 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_FSX0]
set_property src_info {type:XDC file:6 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_DX0]
set_property src_info {type:XDC file:6 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_FSR0]
set_property src_info {type:XDC file:6 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP0_DR0]
set_property src_info {type:XDC file:6 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports McBSP1_DX1]
set_property src_info {type:XDC file:6 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports AD9361_rst]
set_property src_info {type:XDC file:6 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports AD9361_FBCLK]
set_property src_info {type:XDC file:6 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21 [get_ports AD9361_ENABLE]
set_property src_info {type:XDC file:6 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports AD9361_SYNC_IN]
set_property src_info {type:XDC file:6 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports AD9361_EN_AGC]
set_property src_info {type:XDC file:6 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports AD9361_TXNRX]
set_property src_info {type:XDC file:6 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports AD9361_SPI_CLK]
set_property src_info {type:XDC file:6 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports AD9361_SPI_DI]
set_property src_info {type:XDC file:6 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports AD9361_SPI_DO]
set_property src_info {type:XDC file:6 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports AD9361_SPI_ENB]
set_property src_info {type:XDC file:6 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports AD9361_SPI_SEL]
set_property src_info {type:XDC file:6 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_ENABLE]
set_property src_info {type:XDC file:6 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SYNC_IN]
set_property src_info {type:XDC file:6 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN_AGC]
set_property src_info {type:XDC file:6 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_TXNRX]
set_property src_info {type:XDC file:6 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_CLK]
set_property src_info {type:XDC file:6 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_DI]
set_property src_info {type:XDC file:6 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_DO]
set_property src_info {type:XDC file:6 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_ENB]
set_property src_info {type:XDC file:6 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_SPI_SEL]
set_property src_info {type:XDC file:6 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AD9361_rst]
set_property src_info {type:XDC file:6 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15 [get_ports AD9361_10M_OUT]
set_property src_info {type:XDC file:6 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports AD9361_10M_IN]
set_property src_info {type:XDC file:6 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AD9361_10M_OUT]
set_property src_info {type:XDC file:6 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports AD9361_10M_IN]
set_property src_info {type:XDC file:6 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk2AD9361 -max 0.500 [get_ports {AD9361_P1_D} ]
set_property src_info {type:XDC file:6 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk2AD9361 -min -0.500 [get_ports {AD9361_P1_D} ]
current_instance u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:12 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Rx/u_flatten_wrapper/u_axis_data_fifo_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:13 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance u_Tx/u_PSK_Modulation/u_axis_data_fifo_cdc_3/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:14 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
