# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-579-LiPtPDesktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/proc_sys_reset_gen_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/clk_wiz_32M768_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/clk_wiz_128M_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/carrier_gen_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/fir_compiler_0_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/NCO_DDS_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/Multiplier_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/LPF_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/err_detect_BPSK_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/err_detect_QPSK_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/gardner_shift_ram_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/interp_smoothing_filter_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/Costas_LPF_shift_ram_stub.v
      ./.Xil/Vivado-579-LiPtPDesktop/realtime/axis_data_fifo_AD_DA_stub.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/vendor/AD9361_1RT_FDD.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/AXI_2x.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Abs.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Bits_Flatten.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Clock_Gen_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Depacketizer.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Div_clk32M768.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Error_Detect_Ctrl.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Gardner_Corrector.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Gardner_IQ_Preprocess.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Gardner_Timing_Error.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/NCO_Phase.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/NCO_cos_sin.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/NCO_rx_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/PN_Gen.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/PSK_Detection.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/PSK_Mod.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/PSK_Modulation_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/PSK_Signal_Extend.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Packetizer.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Rx_BD.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Rx_PD.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Rx_SD.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Rx_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/SPB_Detection_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Truncate_IQ.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Tx_Data.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/Tx_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/utils/constant.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/costas_loop_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/gardner_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/interpolation_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/utils/sync_FIFO.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/timing_error_wrapper.v
      /home/liptp/courses_2025/general_ex_6/sdr-psk-fpga-2025/verilog/top_wrapper.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-579-LiPtPDesktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
